services:

  janeway-postgres:
    image: postgres:12
    networks:
      - janeway-net
    volumes:
      - ./dockervols/postgres-data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}"
    environment:
      - "POSTGRES_PASSWORD=${DB_PASSWORD}"
      - "POSTGRES_USER=${DB_USER}"
      - "POSTGRES_DB=${DB_NAME}"
    depends_on:
      - janeway-pgadmin

  janeway-pgadmin:
    image: dpage/pgadmin4
    networks:
      - janeway-net
    user: root
    ports:
      - "${PGADMIN_PORT}:80"
    volumes:
      - ./dockervols/pgadmin:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=dev@janeway.systems
      - "PGADMIN_DEFAULT_PASSWORD=${DB_PASSWORD}"
      - PG_ADMIN_LISTEN_ADDRESS=0.0.0.0
      - GUNICORN_THREADS=2
      - PGADMIN_SERVER_JSON_FILE=/var/lib/pgadmin/servers.json
      - PGADMIN_CONFIG_SERVER_MODE=False
      - PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False

  janeway-debug-smtp:
    # Use same python as janeway-web to reduce the number of images
    networks:
      - janeway-net
    image: python:3.8
    entrypoint: python -u -m smtpd -c DebuggingServer -n 0.0.0.0:1025

  start_janeway_dependencies:
    image: dadarek/wait-for-dependencies
    networks:
      - janeway-net
    depends_on:
     - "janeway-postgres"
     - "janeway-debug-smtp"
     - "copy-janeway-static"
    command: "janeway-postgres:${DB_PORT}"

  copy-janeway-static:
    build:
      context: .
      dockerfile: compose/copystatic.dockerfile
    volumes:
      - ./dockervols/static:/vol/janeway/src/staticDynamic
      - ./dockervols/xsl:/vol/janeway/src/transform/xslDynamic

  janeway-web:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - janeway-net
    volumes:
      - ./dockervols/files:/vol/janeway/src/files
      - ./dockervols/plugins:/vol/janeway/src/plugins
      - ./dockervols/lib:/vol/janeway/lib
      - ./dockervols/janeway:/var/www/janeway/
      - ./dockervols/run:/run
      - ./dockervols/cron:/var/spool/cron/crontabs
      - tmp:/tmp # Used for Nginx socket and Janeway install
    environment:
      - DB_HOST
      - DB_PORT
      - DB_PASSWORD
      - DB_USER
      - DB_NAME
      - JANEWAY_PORT
      - NOSE_INCLUDE_EXE=1
      - JANEWAY_EMAIL_BACKEND
      - JANEWAY_EMAIL_HOST
      - JANEWAY_EMAIL_PORT
      - JANEWAY_EMAIL_USE_TLS
      - JANEWAY_ENABLE_ORCID
      - JANEWAY_PRESS_NAME
      - JANEWAY_PRESS_DOMAIN
      - JANEWAY_PRESS_DOMAIN_SCHEME
      - JANEWAY_JOURNAL_DOMAINS
      - JANEWAY_JOURNAL_DOMAIN_SCHEMES
      - JANEWAY_DEFAULT_JOURNAL_INDEX
      - JANEWAY_PRESS_CONTACT
      - JANEWAY_JOURNAL_CODE
      - JANEWAY_JOURNAL_NAME
      - DJANGO_SUPERUSER_USERNAME
      - DJANGO_SUPERUSER_EMAIL
      - DJANGO_SUPERUSER_PASSWORD
      - DJANGO_DEBUG
      - INSTALL_CRON
      - INSTALL_PANDOC_PLUGIN
      - INSTALL_CUSTOMSTYLING_PLUGIN
      - INSTALL_PORTICO_PLUGIN
      - INSTALL_IMPORTS_PLUGIN
      - INSTALL_DOAJ_TRANSPORTER_PLUGIN
      - INSTALL_BACK_CONTENT_PLUGIN
      - INSTALL_REPORTING_PLUGIN
    depends_on:
      - "start_janeway_dependencies"

  janeway-nginx:
    ports:
      - "${JANEWAY_PORT}:${JANEWAY_PORT}"
    image: nginx:latest
    environment:
      - JANEWAY_PORT
    networks:
      - janeway-net
    volumes:
      - ./compose/nginx.conf:/etc/nginx/nginx.conf
      - ./compose/wait-for-janeway.sh:/scripts/wait-for-janeway.sh
      - ./dockervols/janeway:/var/www/janeway/
      - tmp:/tmp # Used for Nginx socket and Janeway install
      - ./dockervols/static:/vol/janeway/src/static
      - ./dockervols/xsl:/vol/janeway/src/transform/xsl
    command: bash -c "chmod +x /scripts/wait-for-janeway.sh && /scripts/wait-for-janeway.sh"

networks:
  janeway-net:

volumes:
  tmp: